# Generated by Django 3.0.6 on 2020-05-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FicheroDeAudio', models.FileField(upload_to='audio')),
                ('Titulo', models.CharField(max_length=30)),
                ('Idioma', models.CharField(max_length=15)),
                ('Duracion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioRegistrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('AudioRegistrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Peticiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=300, unique=True)),
                ('Contrasenya', models.CharField(max_length=300)),
                ('Correo', models.CharField(max_length=300, unique=True)),
                ('FotoDePerfil', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Seguidos', models.ManyToManyField(blank=True, related_name='Seguidores', through='PlayStack.Relacion', to='PlayStack.Usuario')),
                ('SolicitudAmistad', models.ManyToManyField(blank=True, related_name='Solicitudes', through='PlayStack.Peticiones', to='PlayStack.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='relacion',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_users', to='PlayStack.Usuario'),
        ),
        migrations.AddField(
            model_name='relacion',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to='PlayStack.Usuario'),
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsuarioRegistrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Premium', to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('FotoDelPodcast', models.ImageField(upload_to='images')),
                ('Capitulos', models.ManyToManyField(related_name='Capitulos', to='PlayStack.Capitulo')),
                ('Subscriptores', models.ManyToManyField(blank=True, related_name='Suscrito', to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Privado', models.BooleanField()),
                ('Canciones', models.ManyToManyField(blank=True, related_name='PlayLists', to='PlayStack.Cancion')),
                ('UsuarioNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Usuario')),
            ],
            options={
                'unique_together': {('ID', 'UsuarioNombre')},
            },
        ),
        migrations.AddField(
            model_name='peticiones',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_usr', to='PlayStack.Usuario'),
        ),
        migrations.AddField(
            model_name='peticiones',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_usr', to='PlayStack.Usuario'),
        ),
        migrations.CreateModel(
            name='NoPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumSalt', models.IntegerField()),
                ('pidePremium', models.BooleanField(default=False)),
                ('UsuarioRegistrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NoPremium', to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Interlocutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Podcasts', models.ManyToManyField(blank=True, related_name='Participan', to='PlayStack.Podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Canciones', models.ManyToManyField(blank=True, related_name='Generos', to='PlayStack.Cancion')),
            ],
        ),
        migrations.CreateModel(
            name='CreadorContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsuarioRegistrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CreadorContenido', to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('PlayList', models.ManyToManyField(blank=True, related_name='Carpetas', to='PlayStack.PlayList')),
            ],
        ),
        migrations.AddField(
            model_name='cancion',
            name='UsuariosComoFavorita',
            field=models.ManyToManyField(blank=True, related_name='Favoritas', to='PlayStack.Usuario'),
        ),
        migrations.AddField(
            model_name='audio',
            name='CreadorDeContenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.CreadorContenido'),
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30, unique=True)),
                ('Foto', models.ImageField(upload_to='images')),
                ('PaisDeNacimiento', models.CharField(max_length=30)),
                ('Canciones', models.ManyToManyField(blank=True, related_name='Artistas', to='PlayStack.Cancion')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAlbum', models.CharField(max_length=100)),
                ('FotoDelAlbum', models.ImageField(upload_to='images')),
                ('Fecha', models.DateField()),
                ('Canciones', models.ManyToManyField(related_name='Albunes', to='PlayStack.Cancion')),
            ],
        ),
        migrations.CreateModel(
            name='AudioEscuchado',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.DateTimeField()),
                ('Audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Audio')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Usuario')),
            ],
            options={
                'unique_together': {('Usuario', 'Audio', 'TimeStamp')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='audio',
            unique_together={('ID', 'CreadorDeContenido')},
        ),
    ]
