# Generated by Django 3.0.3 on 2020-03-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('Nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('PaisDeNacimiento', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('FicheroDeAudio', models.FileField(upload_to='')),
                ('Titulo', models.CharField(max_length=30)),
                ('Idioma', models.CharField(max_length=15)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Duracion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PlayStack.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='CreadorContenido',
            fields=[
                ('Nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='NoPremium',
            fields=[
                ('Nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PlayStack.Usuario')),
                ('NumSalt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PlayStack.Audio')),
                ('Resumen', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('NombrePremium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('Contrasenya', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=100)),
                ('FotoDePerfil', models.ImageField(upload_to='')),
                ('Seguidos', models.ManyToManyField(related_name='_usuario_Seguidos_+', to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SerFavorita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Audio')),
                ('UsuarioNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('UsuarioNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AudioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Audio')),
                ('GeneroID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Componer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistaNombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Artista')),
                ('Audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Almacenar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarpetaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Carpeta')),
                ('PlayListID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.PlayList')),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='CreadorDeContenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.CreadorContenido'),
        ),
    ]
