# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAlbum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30, unique=True)),
                ('PaisDeNacimiento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FicheroDeAudio', models.FileField(upload_to=b'')),
                ('Titulo', models.CharField(max_length=30)),
                ('Idioma', models.CharField(max_length=15)),
                ('Duracion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='PlayStack.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='PlayStack.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CreadorContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCreador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Canciones', models.ManyToManyField(blank=True, related_name='Generos', to='PlayStack.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Interlocutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NoPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='PlayStack.Usuario')),
                ('NumSalt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Privado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Capitulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Capitulo')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePremium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='PlayStack.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=25, unique=True)),
                ('Contrasenya', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=100, unique=True)),
                ('FotoDePerfil', models.ImageField(upload_to=b'')),
                ('Seguidos', models.ManyToManyField(blank=True, related_name='_usuario_Seguidos_+', to='PlayStack.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='Subscriptores',
            field=models.ManyToManyField(blank=True, related_name='Suscrito', to='PlayStack.Usuario'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='UsuarioNombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.Usuario'),
        ),
        migrations.AddField(
            model_name='interlocutor',
            name='Podcasts',
            field=models.ManyToManyField(blank=True, related_name='Participan', to='PlayStack.Podcast'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='PlayList',
            field=models.ManyToManyField(blank=True, related_name='Carpetas', to='PlayStack.PlayList'),
        ),
        migrations.AddField(
            model_name='audio',
            name='CreadorDeContenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayStack.CreadorContenido'),
        ),
        migrations.AddField(
            model_name='audio',
            name='UsuariosComoFavorita',
            field=models.ManyToManyField(blank=True, related_name='Audios', to='PlayStack.Usuario'),
        ),
        migrations.AddField(
            model_name='artista',
            name='Canciones',
            field=models.ManyToManyField(blank=True, related_name='Artistas', to='PlayStack.Audio'),
        ),
        migrations.AddField(
            model_name='album',
            name='Canciones',
            field=models.ManyToManyField(related_name='Albunes', to='PlayStack.Audio'),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set([('ID', 'UsuarioNombre')]),
        ),
        migrations.AlterUniqueTogether(
            name='audio',
            unique_together=set([('ID', 'CreadorDeContenido')]),
        ),
    ]
