# Generated by Django 3.0.5 on 2020-04-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creadorcontenido',
            name='UsuarioRegistrado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CreadorContenido', to='PlayStack.Usuario'),
        ),
        migrations.AlterField(
            model_name='nopremium',
            name='UsuarioRegistrado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NoPremium', to='PlayStack.Usuario'),
        ),
        migrations.AlterField(
            model_name='premium',
            name='UsuarioRegistrado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Premium', to='PlayStack.Usuario'),
        ),
    ]
