# Generated by Django 2.2.11 on 2020-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Canciones',
            field=models.ManyToManyField(blank=True, related_name='Albunes', to='PlayStack.Audio'),
        ),
    ]
