# Generated by Django 3.0.4 on 2020-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='FicheroDeAudio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FotoDePerfil',
            field=models.ImageField(upload_to=''),
        ),
    ]
