# Generated by Django 3.0.5 on 2020-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0002_auto_20200412_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contrasenya',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='NombreUsuario',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
