# Generated by Django 3.0.6 on 2020-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0002_auto_20200521_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='NumCap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='Fecha',
            field=models.DateField(blank=True),
        ),
    ]
