# Generated by Django 2.2.11 on 2020-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0002_auto_20200309_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Seguidos',
            field=models.ManyToManyField(blank=True, related_name='_usuario_Seguidos_+', to='PlayStack.Usuario'),
        ),
    ]
