# Generated by Django 3.0.6 on 2020-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0003_auto_20200521_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='Fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
