# Generated by Django 3.0.5 on 2020-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0004_auto_20200412_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='Canciones',
            field=models.ManyToManyField(blank=True, related_name='Generos', to='PlayStack.Audio'),
        ),
    ]
