# Generated by Django 3.0.6 on 2020-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0004_auto_20200521_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='NumCap',
        ),
    ]
