# Generated by Django 3.0.5 on 2020-04-15 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0005_auto_20200412_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='Fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='SolicitudAmistad',
            field=models.ManyToManyField(blank=True, related_name='_usuario_SolicitudAmistad_+', to='PlayStack.Usuario'),
        ),
    ]
