# Generated by Django 3.0.6 on 2020-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0005_remove_capitulo_numcap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
