# Generated by Django 3.0.6 on 2020-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0006_auto_20200521_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='Titulo',
            field=models.CharField(max_length=50),
        ),
    ]
