# Generated by Django 3.0.6 on 2020-05-21 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0007_auto_20200521_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='Foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
