# Generated by Django 3.0.6 on 2020-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0008_genero_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='Duracion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
