# Generated by Django 3.0.6 on 2020-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayStack', '0010_auto_20200521_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='interlocutor',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
